### ISSUE TITLE
Joystick/Gamepad Config page doesn't populate with commands

### ISSUE THREAD

**Issue by AchillesPDX** [FalconChristmas/fpp-arcade#2]
It's entirely possible that I just don't fully understand how to set this up, but installing the plugin in FPP 7.5 seems to "mostly" work except I can't seem to assign any commands to the gamepad buttons. I have a PS3 controller as well as an Xbox Series X controller, and both of them show up on the Joystick/Gamepad Config page, but the dropdowns for the commands are empty.
<img width="867" alt="Screenshot 2024-01-28 at 5 46 40 PM" src="https://github.com/FalconChristmas/fpp-arcade/assets/9002045/1832f05c-1c26-433b-b760-a2951f07ef44">

**Comment by AchillesPDX** [comment]
Ah hah! Turns out it's an issue with the name of the game controller. Swapped it out for an X-box One S controller and everything works. I'm assuming it's the "|" symbol in the Series S|X Controller name? Same problem with "Sony PLAYSTATION(R)3 Controller" and I assume it's the "(" and ")" screwing things up.

**Comment by patdelaney** [comment]
@dkulp I believe you fixed a similar issue that for that arcade board in October 2023
https://www.amazon.com/gp/product/B01N09SO20/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
